Removed "remove sub-techniques"
f-bader/SentinelARConverter pull request #38
Opened 2024-06-19 14:47 UTC by Konverto-MartinGasser

With commit [3f4ed3c](https://github.com/f-bader/SentinelARConverter/commit/3f4ed3ce6e5a1346042f03277e430b24cd6494b1) MITRE sub-techniques should be supported and do not require to be removed anymore.

2024-06-19 15:32 UTC, f-bader commented
I guess this is only true if the api version is current enough. See #37 
My solution would be to validate that the selected api version is above this threshold and only then allow subtechniques

2024-06-19 15:46 UTC, f-bader commented
Double checked the documentation and it's not as easy as to just keep them. There needs to be the container with, and a container without the subrechniques.

Minimum API version is indeed [`2023-12-01-preview`](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2023-12-01-preview/AlertRules.json)

```json
"tactics": [
    "Reconnaissance"
],
"techniques": [
    "T1589",
    "T1592",
    "T1598"
],
"subTechniques": [
    "T1589.001",
    "T1592.001"
]
```

@Konverto-MartinGasser do you feel up for the task adding this including tests or rather wait until I have the time to implement it?

2024-06-20 14:54 UTC, Konverto-MartinGasser commented
I was able to implement the function and do some local testing/deploying, which was working as expected. Tomorrow I will try to create matching tests, but honestly, I don't think that I succeed. I'll let you know how it went.

2024-06-20 16:23 UTC, f-bader commented
Very cool. If you need help with the tests let me know. Happy to help

2024-06-21 12:42 UTC, Konverto-MartinGasser commented
Hey @f-bader, could you kindly take a look at my changes and especially on those tests I've written? I've never worked with test-files so far so I'm not sure I did the right thing ( at least they are not failing ;) )
I'm also not quite happy how I merge the properties relevantTechniques, subTechniques and techniques when converting from ARM to YAML. Maybe you have a suggestion on how to improve it?

Thanks

2024-06-21 13:29 UTC, f-bader commented
Will do but most likely next week

2024-07-21 20:00 UTC, f-bader requested changes

2024-07-21 20:05 UTC, f-bader commented on src/public/Convert-SentinelARArmToYaml.ps1
> +                            if (-not($AnalyticsRuleCleaned[$KeyName])) {
```suggestion
                            if ( -not $AnalyticsRuleCleaned.Contains($KeyName) ) {
```

2024-07-21 20:52 UTC, f-bader approved these changes

2024-07-21 20:53 UTC, merged

2024-07-21 20:53 UTC, f-bader commented
@Konverto-MartinGasser Amazing work and sorry it took me so long to validate and merge this.